apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  hosts:
  - "longhorn.bonnell.me.uk"
  gateways:
  - longhorn-frontend
  http:
    - route:
      - destination:
          host: longhorn-frontend
          port:
            number: 80
