apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: longhorn-frontend
      protocol: HTTP
    hosts:
    - "longhorn.bonnell.me.uk"
