apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-gateway
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-loadbalance/base
    repoURL: 'https://github.com/sjbuk/k83.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true