apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
  - port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: argocd-secret
    hosts:
    - "argocd.dev.bonnell.me.uk"
