apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: argocd-server
      protocol: HTTP
    hosts:
    - "argocd.dev.bonnell.me.uk"
