
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  # You'll usually want to add your resources to the argocd namespace.
  namespace: kyverno
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # Add labels to your application object.
  labels:
    name: kyverno
spec:
  # The project the application belongs to.
  project: default
  source:
    repoURL: 'https://kyverno.github.io/kyverno/'
    targetRevision: 2.7.1
    chart: kyverno
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
