apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ssl-zero
  namespace: kube-system
spec:
  acme:
    # The ACME server URL
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: 6yny0w0AvEqIwsxz2ZzTtw
      keySecretRef:
        name: zero-sll-eabsecret
        key: secret
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: zerossl-prod
       # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token